apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dnszones.itlusions.io
spec:
  group: itlusions.io 
  scope: Namespaced
  names:
    plural: dnszones
    singular: dnszone
    kind: DNSZone
    shortNames:
      - dz
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                zone:
                  type: string
                records:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                        enum: [A, CNAME, TXT, SRV]
                      name:
                        type: string
                      value:
                        type: string
                      ttl:
                        type: integer
                      priority:
                        type: integer
                      weight:
                        type: integer
                      port:
                        type: integer
