apiVersion: v1
kind: ServiceAccount
metadata:
  name: dns-operator
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dns-operator
rules:
  - apiGroups: ["dns.example.com"]
    resources: ["dnszones"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dns-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dns-operator
subjects:
  - kind: ServiceAccount
    name: dns-operator
    namespace: kube-system
